language: node_js
os: linux
dist: xenial
node_js:
- 12
services:
  - mysql
env:
  - DB_USER=travis
  - DB_PASS=
before_install:
  - mysql -e 'CREATE DATABASE test;'
script:
  - npm run lint
  - npm run test:ci
