openapi: '3.0.2'
info:
  title: Typescript project
  description: OpenApi Docs
  version: '1.0'
servers:
  - url: https://localhost:3000

paths:
  /:
    get:
      summary: Hello World
      description: 'Hello World route'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref:  '#/components/schemas/hello-response'

components:
  schemas:
    hello-response:
      type: object
      properties:
        msg:
          type: string
          default: hello world

